language: android
android:
  components:
    - android-8
    - build-tools-23.0.2

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build